local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("sound", "|cff7f58dbBeware of Yeti|r", [[Interface\Addons\ShardsSoundPack\sound\Beware of Yeti.ogg]])
LSM:Register("sound", "|cff7f58dbChicken Brain|r", [[Interface\Addons\ShardsSoundPack\sound\Chicken Brain.ogg]])
LSM:Register("sound", "|cff7f58dbCome Shop Browse|r", [[Interface\Addons\ShardsSoundPack\sound\Come Shop Browse.ogg]])
LSM:Register("sound", "|cff7f58dbDo You Need a Carer|r", [[Interface\Addons\ShardsSoundPack\sound\Do You Need a Carer.ogg]])
LSM:Register("sound", "|cff7f58dbFFS Mark|r", [[Interface\Addons\ShardsSoundPack\sound\FFS Mark.ogg]])
LSM:Register("sound", "|cff7f58dbFinal Warning|r", [[Interface\Addons\ShardsSoundPack\sound\Final Warning.ogg]])
LSM:Register("sound", "|cff7f58dbFunnel Cake|r", [[Interface\Addons\ShardsSoundPack\sound\Funnel Cake.mp3]])
LSM:Register("sound", "|cff7f58dbGet Back to Work|r", [[Interface\Addons\ShardsSoundPack\sound\Get Back to Work.mp3]])
LSM:Register("sound", "|cff7f58dbGolden Legendary|r", [[Interface\Addons\ShardsSoundPack\sound\Golden Legendary.mp3]])
LSM:Register("sound", "|cff7f58dbHobbit - Cheese Knife|r", [[Interface\Addons\ShardsSoundPack\sound\Hobbit - Cheese Knife.mp3]])
LSM:Register("sound", "|cff7f58dbHobbit - Dragon|r", [[Interface\Addons\ShardsSoundPack\sound\Hobbit - Dragon.mp3]])
LSM:Register("sound", "|cff7f58dbHobbit - Good Morning|r", [[Interface\Addons\ShardsSoundPack\sound\Hobbit - Good Morning.mp3]])
LSM:Register("sound", "|cff7f58dbHobbit - No Way|r", [[Interface\Addons\ShardsSoundPack\sound\Hobbit - No Way.mp3]])
LSM:Register("sound", "|cff7f58dbHobbit - Nooooo|r", [[Interface\Addons\ShardsSoundPack\sound\Hobbit - Nooooo.mp3]])
LSM:Register("sound", "|cff7f58dbHobbit - Scream|r", [[Interface\Addons\ShardsSoundPack\sound\Hobbit - Scream.mp3]])
LSM:Register("sound", "|cff7f58dbHobbit - Stop|r", [[Interface\Addons\ShardsSoundPack\sound\Hobbit - Stop.mp3]])
LSM:Register("sound", "|cff7f58dbI Don't Have Words|r", [[Interface\Addons\ShardsSoundPack\sound\I Don't Have Words.ogg]])
LSM:Register("sound", "|cff7f58dbLegendary|r", [[Interface\Addons\ShardsSoundPack\sound\Legendary.mp3]])
LSM:Register("sound", "|cff7f58dbLeya Scream|r", [[Interface\Addons\ShardsSoundPack\sound\Leya Scream.mp3]])
LSM:Register("sound", "|cff7f58dbLiterally Confused|r", [[Interface\Addons\ShardsSoundPack\sound\Literally Confused.ogg]])
LSM:Register("sound", "|cff7f58dbMax Fight Cops|r", [[Interface\Addons\ShardsSoundPack\sound\Max Fight Cops.mp3]])
LSM:Register("sound", "|cff7f58dbMoaning (18+)|r", [[Interface\Addons\ShardsSoundPack\sound\Moaning (18+).mp3]])
LSM:Register("sound", "|cff7f58dbMy Ass is Puckered|r", [[Interface\Addons\ShardsSoundPack\sound\My Ass is Puckered.mp3]])
LSM:Register("sound", "|cff7f58dbNext Time|r", [[Interface\Addons\ShardsSoundPack\sound\Next Time.mp3]])
LSM:Register("sound", "|cff7f58dbRaid Log Life|r", [[Interface\Addons\ShardsSoundPack\sound\Raid Log Life.ogg]])
LSM:Register("sound", "|cff7f58dbSea Shanty 2 (Remix)|r", [[Interface\Addons\ShardsSoundPack\sound\Sea Shanty 2 (Remix).mp3]])
LSM:Register("sound", "|cff7f58dbSea Shanty 2|r", [[Interface\Addons\ShardsSoundPack\sound\Sea Shanty 2.mp3]])
LSM:Register("sound", "|cff7f58dbShit Your Own Pants|r", [[Interface\Addons\ShardsSoundPack\sound\Shit Your Own Pants.ogg]])
LSM:Register("sound", "|cff7f58dbSkill Issue|r", [[Interface\Addons\ShardsSoundPack\sound\Skill Issue.mp3]])
LSM:Register("sound", "|cff7f58dbSkovald|r", [[Interface\Addons\ShardsSoundPack\sound\Skovald.ogg]])
LSM:Register("sound", "|cff7f58dbSmooth Brain|r", [[Interface\Addons\ShardsSoundPack\sound\Smooth Brain.ogg]])
LSM:Register("sound", "|cff7f58dbStep Bro|r", [[Interface\Addons\ShardsSoundPack\sound\Step Bro.mp3]])
LSM:Register("sound", "|cff7f58dbStupid Fart|r", [[Interface\Addons\ShardsSoundPack\sound\Stupid Fart.ogg]])
LSM:Register("sound", "|cff7f58dbTokyo Drift|r", [[Interface\Addons\ShardsSoundPack\sound\Tokyo Drift.mp3]])
LSM:Register("sound", "|cff7f58dbWe Go Again|r", [[Interface\Addons\ShardsSoundPack\sound\We Go Again.ogg]])
LSM:Register("sound", "|cff7f58dbYer Did It Champion|r", [[Interface\Addons\ShardsSoundPack\sound\Yer Did It Champion.mp3]])
LSM:Register("sound", "|cff7f58dbYour Day (Rick)|r", [[Interface\Addons\ShardsSoundPack\sound\Your Day (Rick).mp3]])
LSM:Register("sound", "|cff7f58dbYour Day|r", [[Interface\Addons\ShardsSoundPack\sound\Your Day.ogg]])
