local LSM = LibStub("LibSharedMedia-3.0")

LSM:Register("sound", "|cff7f58dbBeware of Yeti|r", [[Interface\Addons\ShardsSoundPack\sound\Beware of Yeti.ogg]])
LSM:Register("sound", "|cff7f58dbChicken Brain|r", [[Interface\Addons\ShardsSoundPack\sound\Chicken Brain.ogg]])
LSM:Register("sound", "|cff7f58dbCome Shop Browse|r", [[Interface\Addons\ShardsSoundPack\sound\Come Shop Browse.ogg]])
LSM:Register("sound", "|cff7f58dbDo You Need a Carer|r", [[Interface\Addons\ShardsSoundPack\sound\Do You Need a Carer.ogg]])
LSM:Register("sound", "|cff7f58dbFFS Mark|r", [[Interface\Addons\ShardsSoundPack\sound\FFS Mark.ogg]])
LSM:Register("sound", "|cff7f58dbFinal Warning|r", [[Interface\Addons\ShardsSoundPack\sound\Final Warning.ogg]])
LSM:Register("sound", "|cff7f58dbI Don't Have Words|r", [[Interface\Addons\ShardsSoundPack\sound\I Don't Have Words.ogg]])
LSM:Register("sound", "|cff7f58dbLiterally Confused|r", [[Interface\Addons\ShardsSoundPack\sound\Literally Confused.ogg]])
LSM:Register("sound", "|cff7f58dbRaid Log Life|r", [[Interface\Addons\ShardsSoundPack\sound\Raid Log Life.ogg]])
LSM:Register("sound", "|cff7f58dbShit Your Own Pants|r", [[Interface\Addons\ShardsSoundPack\sound\Shit Your Own Pants.ogg]])
LSM:Register("sound", "|cff7f58dbSkovald|r", [[Interface\Addons\ShardsSoundPack\sound\Skovald.ogg]])
LSM:Register("sound", "|cff7f58dbSmooth Brain|r", [[Interface\Addons\ShardsSoundPack\sound\Smooth Brain.ogg]])
LSM:Register("sound", "|cff7f58dbStupid Fart|r", [[Interface\Addons\ShardsSoundPack\sound\Stupid Fart.ogg]])
LSM:Register("sound", "|cff7f58dbWe Go Again|r", [[Interface\Addons\ShardsSoundPack\sound\We Go Again.ogg]])
LSM:Register("sound", "|cff7f58dbYour Day|r", [[Interface\Addons\ShardsSoundPack\sound\Your Day.ogg]])
